version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    # Placeholder configuration for lab use only.

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  neo4j:
    image: neo4j:5.19
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    # Intended for controlled vulnerability simulations only.
